/* Generated By:JJTree: Do not edit this line. ASTInterpolation.java */

package org.geoserver.wcs.kvp.rangesubset;

public @SuppressWarnings("all") class ASTInterpolation extends SimpleNode {
  public ASTInterpolation(int id) {
    super(id);
  }

  public ASTInterpolation(RangeSubsetParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RangeSubsetParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
