/* Generated By:JJTree&JavaCC: Do not edit this line. RangeSubsetParserConstants.java */
package org.geoserver.wcs.kvp.rangesubset;

public @SuppressWarnings("all") interface RangeSubsetParserConstants {

  int EOF = 0;
  int LP = 5;
  int RP = 6;
  int COMMA = 7;
  int SEMICOLON = 8;
  int COLON = 9;
  int IDENTIFIER = 10;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"[\"",
    "\"]\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "<IDENTIFIER>",
  };

}
