/* Generated By:JJTree: Do not edit this line. ASTFieldSubset.java */

package org.geoserver.wcs.kvp.rangesubset;

public @SuppressWarnings("all") class ASTFieldSubset extends SimpleNode {
  public ASTFieldSubset(int id) {
    super(id);
  }

  public ASTFieldSubset(RangeSubsetParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(RangeSubsetParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
