/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs.validation;

import net.opengis.wcs.ClosureType;
import net.opengis.wcs.TypedLiteralType;

/**
 * A sample validator interface for {@link net.opengis.wcs.ValueRangeType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ValueRangeTypeValidator {
    boolean validate();

    boolean validateMin(TypedLiteralType value);
    boolean validateMax(TypedLiteralType value);
    boolean validateAtomic(boolean value);
    boolean validateClosure(ClosureType value);
    boolean validateSemantic(String value);
    boolean validateType(String value);
}
