/* Generated By:JJTree: Do not edit this line. .\RangeSubsetParserTreeConstants.java */

package org.geoserver.wcs.kvp.rangesubset;

public @SuppressWarnings("all") interface RangeSubsetParserTreeConstants
{
  public int JJTRANGESUBSET = 0;
  public int JJTFIELDSUBSET = 1;
  public int JJTVOID = 2;
  public int JJTAXISSUBSET = 3;
  public int JJTFIELDID = 4;
  public int JJTAXISID = 5;
  public int JJTINTERPOLATION = 6;
  public int JJTKEY = 7;


  public String[] jjtNodeName = {
    "RangeSubset",
    "FieldSubset",
    "void",
    "AxisSubset",
    "FieldId",
    "AxisId",
    "Interpolation",
    "Key",
  };
}
