/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs.validation;

import net.opengis.wcs.AxisDescriptionType;

/**
 * A sample validator interface for {@link net.opengis.wcs.AxisDescriptionType1}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AxisDescriptionType1Validator {
    boolean validate();

    boolean validateAxisDescription(AxisDescriptionType value);
}
