/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs.validation;

import net.opengis.gml.CodeListType;

import net.opengis.wcs.AxisDescriptionType;
import net.opengis.wcs.AxisDescriptionType1;
import net.opengis.wcs.ClosureType;
import net.opengis.wcs.ContentMetadataType;
import net.opengis.wcs.CoverageDescriptionType;
import net.opengis.wcs.CoverageOfferingBriefType;
import net.opengis.wcs.CoverageOfferingType;
import net.opengis.wcs.DescribeCoverageType;
import net.opengis.wcs.DomainSetType;
import net.opengis.wcs.GetCapabilitiesType;
import net.opengis.wcs.GetCoverageType;
import net.opengis.wcs.InterpolationMethodType;
import net.opengis.wcs.IntervalType;
import net.opengis.wcs.KeywordsType;
import net.opengis.wcs.LonLatEnvelopeType;
import net.opengis.wcs.MetadataLinkType;
import net.opengis.wcs.RangeSetType;
import net.opengis.wcs.RangeSetType1;
import net.opengis.wcs.ServiceType;
import net.opengis.wcs.SpatialDomainType;
import net.opengis.wcs.SpatialSubsetType;
import net.opengis.wcs.SupportedCRSsType;
import net.opengis.wcs.SupportedFormatsType;
import net.opengis.wcs.SupportedInterpolationsType;
import net.opengis.wcs.TimePeriodType;
import net.opengis.wcs.TimeSequenceType;
import net.opengis.wcs.TypedLiteralType;
import net.opengis.wcs.WCSCapabilitiesType;
import net.opengis.wcs.WCSCapabilityType;

import org.eclipse.emf.common.util.EMap;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link net.opengis.wcs.DocumentRoot}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DocumentRootValidator {
    boolean validate();

    boolean validateMixed(FeatureMap value);
    boolean validateXMLNSPrefixMap(EMap value);
    boolean validateXSISchemaLocation(EMap value);
    boolean validateAxisDescription(AxisDescriptionType1 value);
    boolean validateAxisDescription1(AxisDescriptionType value);
    boolean validateCapability(WCSCapabilityType value);
    boolean validateContentMetadata(ContentMetadataType value);
    boolean validateCoverageDescription(CoverageDescriptionType value);
    boolean validateCoverageOffering(CoverageOfferingType value);
    boolean validateCoverageOfferingBrief(CoverageOfferingBriefType value);
    boolean validateDescribeCoverage(DescribeCoverageType value);
    boolean validateDescription(String value);
    boolean validateDomainSet(DomainSetType value);
    boolean validateFormats(CodeListType value);
    boolean validateGetCapabilities(GetCapabilitiesType value);
    boolean validateGetCoverage(GetCoverageType value);
    boolean validateInterpolationMethod(InterpolationMethodType value);
    boolean validateInterval(IntervalType value);
    boolean validateKeywords(KeywordsType value);
    boolean validateLonLatEnvelope(LonLatEnvelopeType value);
    boolean validateMetadataLink(MetadataLinkType value);
    boolean validateName(String value);
    boolean validateRangeSet(RangeSetType1 value);
    boolean validateRangeSet1(RangeSetType value);
    boolean validateService(ServiceType value);
    boolean validateSingleValue(TypedLiteralType value);
    boolean validateSpatialDomain(SpatialDomainType value);
    boolean validateSpatialSubset(SpatialSubsetType value);
    boolean validateSupportedCRSs(SupportedCRSsType value);
    boolean validateSupportedFormats(SupportedFormatsType value);
    boolean validateSupportedInterpolations(SupportedInterpolationsType value);
    boolean validateTemporalDomain(TimeSequenceType value);
    boolean validateTemporalSubset(TimeSequenceType value);
    boolean validateTimePeriod(TimePeriodType value);
    boolean validateTimeSequence(TimeSequenceType value);
    boolean validateWCSCapabilities(WCSCapabilitiesType value);
    boolean validateClosure(ClosureType value);
    boolean validateSemantic(String value);
    boolean validateType(String value);
}
