/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs.validation;

import net.opengis.wcs.DescribeCoverageType1;
import net.opengis.wcs.GetCapabilitiesType1;
import net.opengis.wcs.GetCoverageType1;

/**
 * A sample validator interface for {@link net.opengis.wcs.RequestType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RequestTypeValidator {
    boolean validate();

    boolean validateGetCapabilities(GetCapabilitiesType1 value);
    boolean validateDescribeCoverage(DescribeCoverageType1 value);
    boolean validateGetCoverage(GetCoverageType1 value);
}
