/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package net.opengis.wcs.validation;

import net.opengis.wcs.ExceptionType;
import net.opengis.wcs.RequestType;
import net.opengis.wcs.VendorSpecificCapabilitiesType;

/**
 * A sample validator interface for {@link net.opengis.wcs.WCSCapabilityType}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WCSCapabilityTypeValidator {
    boolean validate();

    boolean validateRequest(RequestType value);
    boolean validateException(ExceptionType value);
    boolean validateVendorSpecificCapabilities(VendorSpecificCapabilitiesType value);
    boolean validateUpdateSequence(String value);
    boolean validateVersion(String value);
}
